### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Aericio** [GMNetwork/GM-Commands#1]
# TOP PRIORITY:

- [ ] Add /socialspy (its a huge bug that socialspy is not added *cough cough* @SalmonGER)

# these r useless

- [ ] Add /rules command

- [ ] Add /links command

- [ ] Add /server command (seriously, they ask me what is the server ip)

- [ ] Add /shop command, shows ranks with it.

**Comment by SalmonGER** [comment]
@Aericio Will work on it later I gues

**Comment by Aericio** [comment]
Updated
